### ISSUE TITLE
Add a check to validate the integrity of all core installation files

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/SecurityAnalyzer#11]
The security of DNN is highly important, across the entire ecosystem.  The integrity of the ecosystem requires that we have the tools available to ensure that even deeply rooted files haven't been compromised (e.g., telerik radeditor, provider files, sql data provider files, etc.).

This enhancement should scan all of the core files against a known clean instance of the core files, and report any files that have been altered or removed.

**Comment by cathalconnolly** [comment]
sure, that's already something that Evoq does, but in this case I'm just doing the simple check - feel free to log an enhancement request/submit a pull request for a broader capability

**Comment by WillStrohl** [comment]
Thanks, Cathal. I know Evoq does this already. However, I was merely suggesting that security was important to everyone, and it has an very valid and long lasting impact on the entire ecosystem.  If a Platform instance of DNN is compromised - which is the biggest footprint - then this directly affects the entire ecosystem, which includes Evoq customers.

**Comment by cathalconnolly** [comment]
sure, I appreciate the points - however as all the work that will be done on this module will be by me in my spare time (and any pull requests that come in), I'm simply stating that I only have the time to do a small enhancement and not a larger one 

Note: this module is in the DNN Community area , it isn't a part of the platform source code

**Comment by sleupold** [comment]
security is way too overrated, like backups ;)
we should advice user to re-unzip DNN upgrade package, which should overwrite all static files (and run /install/install.aspx?mode=installresources to do same for core modules). this will however not affect installed 3rd party extensions nor files storing custom information (like web.config and CK editor configuration) and any file added by a hacker. 
If the installer tracks all files being installed, a scanner could check for any files outside portals being added - however, we need to train module developers first not to store any living files in the module folder...

**Comment by mitchelsellers** [comment]
I think that this is a great idea, but there is the aspect of where to store the "known good" files to be stored.  It should be at a minimum a MD5 checksum validation.

**Comment by cathalconnolly** [comment]
I know the evoq team generates their own signatures and ships it with the product, but frankly I don't have the time to start doing that - a simple switch statement based on assembly version identified hashes will be better than nothing. Im not against doing full codebase signature files, it's just that as a separate OSS module that's an overhead in generation as well as increasing the size of the installer (i.e. we have to ship signature files for each supported release - from memory evoq's files are 700KB, but that's not an issue for them as they update the signatures as part of the evoq release )

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/126 where the new security analyzer is.
