### ISSUE TITLE
Extra checks on host users

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/SecurityAnalyzer#15]
I would add 2 checks:
A. A check for a host user with default credentials (as you get after a default install)
B. A warning if there's a superuser named "host" that is not the "oldest" superuser.

**Comment by sleupold** [comment]
C: if there is a superuser named "host", suggest renaming it (makes it more difficult to test login credentials)
d: same for "admin"

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/127
