### ISSUE TITLE
Highlight Changes Since Last Visit

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/SecurityAnalyzer#17]
The module should log and/or be aware of the last time the admin ran the scans here.  This would allow only the things that have changed since the last scan to be reviewed.  This would make it easier to spot issues that may be new, instead of perhaps getting complacent or "scanning" all of this information and potentially missing something.

For example, if any specific host settings have been updated or added since the last time the scan was run, they might be shown in bold and/or red text.

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/128
