### ISSUE TITLE
Slight Enhancement - File System Search - "rootkit" in form text

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/SecurityAnalyzer#21]
When searching for the term "rootkit" I was surprised to see one result returned under File Results

**File Results
View.ascx (06/15/2016 09:19:49)**

So I searched the DNN Instance with Windows Exporer and found the instance, 

```
C:\**server file structre ** \DesktopModules\DNNCorp\SecurityAnalyzer\View.ascx:
   71                  <div class="dnnFormItem">
   72                      <dnn:label id="plSearchTerm" controlname="txtSearchTerm" runat="server" CssClass="dnnFormRequired"/>
   73:                     <asp:TextBox ID="txtSearchTerm" runat="server" MaxLength="256" Text="rootkit" ValidationGroup="ScannerChecks" />
```

AH! But that's the view.ascx of the actual Security Analyzer

We probably shouldn't remove the view.ascx from review because then it would be a good place to hide things... so perhaps in the returned search results, specific to this file it ignores the text?

**Comment by birksy89** [comment]
I've just this second done the same thing.

It would have been helpful if the tool returned the path of the file, rather than just "view.ascx" as there's 100's of these...

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/130
