### ISSUE TITLE
Slight Enhancement - File System Search - display path

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/SecurityAnalyzer#22]
The File Results when searching return only the name of the file (?)

```
File Results
View.ascx (06/15/2016 09:19:49)
```

We wouldn't' want that to be a link that you'd be encouraged to click... so how about displaying the file path location?

**Comment by ashishpd** [comment]
Great idea, we'd show the full path.

**Comment by rudgr** [comment]
yeah, that would be great!

PS: do you happen to know which view.ascx is meant here?

tx

**Comment by rudgr** [comment]
ah...  could it be that this is the view control of the security analyser module itself? ;-)

`<div class="dnnFormItem">
                    <dnn:label id="plSearchTerm" controlname="txtSearchTerm" runat="server" CssClass="dnnFormRequired"/>
                    <asp:TextBox ID="txtSearchTerm" runat="server" MaxLength="256" Text="rootkit" ValidationGroup="ScannerChecks" />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" Display="Dynamic" 
                        EnableClientScript="true" ControlToValidate="txtSearchTerm" CssClass="dnnFormMessage dnnFormError"
                         resourcekey="SearchTermRequired" ValidationGroup="ScannerChecks"/>
                    <asp:LinkButton ID="cmdSearch" runat="server" CssClass="dnnPrimaryAction" resourcekey="cmdSearch" ValidationGroup="ScannerChecks"/>
                </div>`

maybe it would be an idea to "exclude" that control?
(or at least indicate that this specifix "rootkit" entry is expected?)

**Comment by sleupold** [comment]
the text in view.ascx should be neglectable, as the caption is taken from a resource file

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/130
