### ISSUE TITLE
critical error has occurred

### ISSUE THREAD

**Issue by jdwdigital** [DNNCommunity/SecurityAnalyzer#23]
I installed the module today and it went fine, but when I attempt to run it I get a "critical error has occurred" and the events log shows, amongst other things -- **"InnerException:Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=################' failed."** Note that I obfuscated the PublicKeyToken -- just in case ;-) The site is running DNN 07.03.04 in medium trust.

**Comment by sleupold** [comment]
AFAIK medium trust is not supported - and no longer suggested by Microsoft (there is no security gain over full trust)

**Comment by jdwdigital** [comment]
Thanks. Full Trust is available now with Godaddy new shared hosting accounts using Plesk. I guess it just defaults to "medium" when setup. I'll have a look to see if there are any issues with bumping it up to Full Trust.

**Comment by rtonerii** [comment]
I just want to verify, the website must have full trust to use this module?  I ask because Hostgator only allows up to medium.

**Comment by sleupold** [comment]
you should be able to run the module in medium trust as well, but some tests will not be executed

**Comment by bdukes** [comment]
@rtonerii it probably won't fix your issue in the short term, but you should probably point HostGator to https://support.microsoft.com/en-us/kb/2698981, where they officially recommend avoiding medium trust
