### ISSUE TITLE
CheckDiskAccess always a warning

### ISSUE THREAD

**Issue by mkosse** [DNNCommunity/SecurityAnalyzer#24]
I have changed the settings for the security to one single user that has only access to one folder on my disk. (I checked the permissions) however the CheckDiskAccess keeps giving warnings on this point.

Am i missing something? because it looks like a bug..

**Comment by Timo-Breumelhof** [comment]
I think the analyser is correct. You should remove access for the User group to other folders as the "App pool user" is also a member of the Users group.
(you should change anonymous authentication to apppool user though or the result will be a  site without stylesheets. :-)

**Comment by ashishpd** [comment]
Please read this article for more details. Essentially, one needs to remove Users group from the folders hosting the website(s), and explicitly add the App Pool user to the folder. https://stackoverflow.com/questions/5437723/iis-apppoolidentity-and-file-system-write-access-permissions

**Comment by valadas** [comment]
Moved to https://github.com/dnnsoftware/Dnn.AdminExperience/issues/131
