### ISSUE TITLE
Not detecting SecurityFix201701

### ISSUE THREAD

**Issue by ggiordan** [DNNCommunity/SecurityAnalyzer#27]
Actually, I'm not sure if the issue is with this tool or with the fix.

I've attached a screenshot of the tool's output.

![image](https://user-images.githubusercontent.com/3812056/28636002-bc4aa76e-720a-11e7-9803-6fe8c4885e9c.png)

Here is the patch itself:
![image](https://user-images.githubusercontent.com/3812056/28636068-f34872d2-720a-11e7-8e6f-e6c33c0b2eb7.png)

**Comment by valadas** [comment]
With #42 resolution, I think this will no longer be needed, so I am closing
