### ISSUE TITLE
Site times out before analyzer finishes

### ISSUE THREAD

**Issue by ggiordan** [DNNCommunity/SecurityAnalyzer#28]
The tool works fine on my test sites, but on our production site (which has 400+ portals) but the page times out at our loadbalancer before finishing.

Changing the timeout is not an option, it's set to 30 seconds and "that's that". (for better / worse)

Perhaps, the output could also be written to a file? Or send an email to the site owner (or the logged in user?)

In general when this happens, the request finishes @ the web server, but by that time, the page has been timed out by the LB.

I'd like to capture this valuable information, just thinking about how to get it.

**Comment by valadas** [comment]
@ggiordan , if it still happens in the new security analyzer please open a new issue here: https://github.com/dnnsoftware/Dnn.AdminExperience
