### ISSUE TITLE
Feature Request: Verify/Reset File-Dir Access Permissions

### ISSUE THREAD

**Issue by VashJuan** [DNNCommunity/SecurityAnalyzer#3]
Not sure who else has done this, but as one step for figuring out why an install doesn't work, some folks may have set over-generous permissions throughout their site(s). Might it make sense to go down the main directory trees and verify (with optional reset) these permissions properly?

**Comment by bdukes** [comment]
:+1:

**Comment by bdukes** [comment]
:+1:

**Comment by cathalconnolly** [comment]
typically we see install issues when people have insufficient permissions, or when web.config is marked as read-only (easy to happen if checked out of source control such as TFS), so that would be a good check also

**Comment by valadas** [comment]
@EPTamminga , @bdukes , @mitchelsellers 

I think this is implemented in the new one right? Should we close this?

**Comment by valadas** [comment]
I am closing this to cleanup this repository, if still valid, please open a new issue at https://github.com/dnnsoftware/Dnn.AdminExperience
