### ISSUE TITLE
Not detecting security fix 01.01.01 after installing 01.02.00

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/SecurityAnalyzer#31]
After installing security patch 01.02.00 + security analyzer 08.01.03, i get this warning:

CheckTelerikVulnerability : Check if Telerik component has vulnerability. |   | The  Telerik component vulnerability has not been patched, please go to  http://www.dnnsoftware.com/services/customer-support/success-network/security-fix-june-2017  for detailed information and to download the patch. | Telerik.Web.UI.dll assembly has't been patched.
-- | -- | -- | --

While the june patch was installed previously.

**Comment by galatrash** [comment]
Check this from the Security Analyzer (SA) tab and not the PesronaBar Security (PBS) tab. 
SA is updated to check against the latest Telerik DLL while the PBS is still checking for the older one. The latter will be updated in the next release of DNN 09.02.00 (in about 1.5 to 2 months).

**Comment by Timo-Breumelhof** [comment]
I installed the module on DNN 7 as a test and got this result, so I was using the module..

**Comment by ghost** [comment]
Yes, have also this problem on 8.0.4

**Comment by ashishpd** [comment]
we are fixing it.. The link here needs to be updated. Also, we had wrong link of the hot fix posted on the blog. The link of hot fix is correct now... one needs to re-download and install again (likely repair). The URL on security analyzer will be updated shortly.

**Comment by Timo-Breumelhof** [comment]
Ok Ash, if I understand this correctly, next time there's a security patch I'm going to wait 2 days before installing. This is the second time in 2 months that we patch all our installations and we have to re-do them a day later. As much as I appreciate the effort you are doing, this does really suck if I'm honest.

**Comment by ashishpd** [comment]
Don't do that (wait 2 days :)) @Timo-Breumelhof you are DNN MVP, and I value your timely feedback.

**Comment by Timo-Breumelhof** [comment]
Yes, but we have to re-do 50+ install now... :-( I'll wait next time before I do them all then :-) @ashishpd

**Comment by valadas** [comment]
I am assuming this was fixed after the last comments, so I am closing this issue.
