### ISSUE TITLE
DNN7.3.3 - CheckHttpModules : Check Security Analyzer Http Module	

### ISSUE THREAD

**Issue by MAndrade1980** [DNNCommunity/SecurityAnalyzer#37]
Hi all, I'm running a site using DNN 7.3.3 and the security analyzer tool always fails the site for this check:

CheckHttpModules : Check Security Analyzer Http Module:
The Security Analyzer Http Module haven't initialized in application, please check web.config file to see whether the http module config correctly.

I am not understanding the proposed fix, could someone assist? Any help would be so greatly appreciated!

-  Marco

**Comment by bdukes** [comment]
In your site's `web.config` file, there should be an entry for `DNN.Modules.SecurityAnalyzer.HttpModules.SecurityAnalyzerModule` in the `<modules>` section.  You may want to try re-installing the Security Analyzer extension to see if it gets in place.

**Comment by MAndrade1980** [comment]
That did it! There were permissions issues writing to the web config initially. Thanks Brian, the prompt response is greatly appreciated. 

- Marco
