### ISSUE TITLE
Reference is not set to an instance of an object

### ISSUE THREAD

**Issue by sleupold** [DNNCommunity/SecurityAnalyzer#4]
Installed the module (DNN 7.4.0) and got an immediate error:
bei DNN.Modules.SecurityAnalyzer.Components.Checks.CheckBiography.Execute()
   bei DNN.Modules.SecurityAnalyzer.Components.AuditChecks.DoChecks()
   bei DNN.Modules.SecurityAnalyzer.View.GetAuditResults()
   bei DNN.Modules.SecurityAnalyzer.View.Page_Load(Object sender, EventArgs e)
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Control.LoadRecursive()
   bei System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by cathalconnolly** [comment]
Odd, we tested on multiple versions from 6.2.0-7.4.1 - Were you using the release from https://github.com/DNNCommunity/SecurityAnalyzer/releases ?

**Comment by sleupold** [comment]
yes. does this check perform direct database calls?

**Comment by sleupold** [comment]
Just before, I got a Support request from another user, who installed the module on his site (different DNN Instance)  and uninstalled it and now gets "Error: is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The argument 'portalId' cannot be negative. Parameter name: portalId". I still Need to check for full stack trace.

**Comment by cathalconnolly** [comment]
regarding the check, no it doesn't do any direct database calls, only API. I'm surprised by the error as all the checks are wrapped in error handling-you can view the code at https://github.com/DNNCommunity/SecurityAnalyzer/blob/master/Components/Checks/CheckBiography.cs but as you see we set the check to "unverified", then do the check within a try-catch so any exception would be caught and the results would return "unverified"

**Comment by sleupold** [comment]
I just reviewed the source code and noticed that SearchDatabase doesn't seem to be used anywhere.

**Comment by cathalconnolly** [comment]
it's used here - https://github.com/DNNCommunity/SecurityAnalyzer/blob/master/View.ascx.cs#L67

**Comment by sleupold** [comment]
ah I see - although I doubt, it works properly for numeric columns.

**Comment by sleupold** [comment]
I just uninstalled the module and tried to delete the page.
now I get "Fehler: ist zur Zeit nicht verfügbar. DotNetNuke.Services.Exceptions.ModuleLoadException: Das Argument 'portalId' darf nicht leer sein. Parametername: portalId ---> System.ArgumentOutOfRangeException: Das Argument 'portalId' darf nicht leer sein. Parametername: portalId bei DotNetNuke.Common.Requires.NotNegative(String argName, Int32 argValue) in c:\TeamCity\buildAgent\work\DNN_Platform_740\Packaging\DNN.Platform\DNN Platform\Library\Common\Requires.cs:Zeile 63. bei DotNetNuke.Entities.Tabs.TabVersions.TabVersionSettings.IsVersioningEnabled(Int32 portalId, Int32 tabId) in c:\TeamCity\buildAgent\work\DNN_Platform_740\Packaging\DNN.Platform\DNN Platform\Library\Entities\Tabs\TabVersions\TabVersionSettings.cs:Zeile 74. bei DotNetNuke.Entities.Tabs.TabChangeSettings.GetChangeControlState(Int32 portalId, Int32 tabId) in c:\TeamCity\buildAgent\work\DNN_Platform_740\Packaging\DNN.Platform\DNN Platform\Library\Entities\Tabs\TabChangeSettings.cs:Zeile 46. bei DotNetNuke.Entities.Tabs.TabController.SoftDeleteTabInternal(TabInfo tabToDelete, PortalSettings portalSettings) in c:\TeamCity\buildAgent\work\DNN_Platform_740\Packaging\DNN.Platform\DNN Platform\Library\Entities\Tabs\TabController.cs:Zeile 682. bei DotNetNuke.Entities.Tabs.TabController.SoftDeleteTab(Int32 tabId, PortalSettings portalSettings) in c:\TeamCity\buildAgent\work\DNN_Platform_740\Packaging\DNN.Platform\DNN Platform\Library\Entities\Tabs\TabController.cs:Zeile 1896. bei DotNetNuke.Modules.Admin.Tabs.ManageTabs.DeleteTab(Int32 deleteTabId) bei DotNetNuke.Modules.Admin.Tabs.ManageTabs.OnLoad(EventArgs e) --- Ende der internen Ausnahmestapelüberwachung --- "

**Comment by cathalconnolly** [comment]
it works fine for numeric columns -see the datatypes it searches here - https://github.com/DNNCommunity/SecurityAnalyzer/blob/master/Providers/DataProviders/SqlDataProvider/01.00.00.SqlDataProvider#L59

**Comment by cathalconnolly** [comment]
that looks like an error in DNN platform when deleting a host page - can you please log it to support.dnnsoftware.com

**Comment by ghost** [comment]
Any update on this as I just got the same error trying to delete a page that was under the Host and not the website.?

**Comment by valadas** [comment]
Closing since it is a Dnn issue, not with the module.
