### ISSUE TITLE
RFC: Future of this module

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/SecurityAnalyzer#42]
We need to discuss the end of this module:

Is PR #11 ok to merge and publish a new release or do we need to adjust some wording ?

What do we do with the existing issues, what needs to move to DnnPlatform, what needs to be closed ?

We need to document the upgrade issue in the Dnn upgrade path Wiki page and in release notes ?

We also need to add wording to not install this module on Dnn 9

@DNNCommunity/module-development-team please comment

**Comment by EPTamminga** [comment]
Change code so the the SA does not work on V9 with a message on startup that the PB version is to be used?

**Comment by mitchelsellers** [comment]
I took a stab at a few recommended text changes: https://github.com/DNNCommunity/DNN.SecurityAnalyzer/pull/41#pullrequestreview-172515111

@EPTamminga @valadas Any thoughts?

**Comment by EPTamminga** [comment]
@mitchelsellers: no further comments LGTM.

**Comment by valadas** [comment]
Looks good to me, I gonna go through the open issues and try to decide if they should be just closes or moved to the main repo, I will comment here if I have hesitations on some of them.

**Comment by valadas** [comment]
Ok, I closed and or moved all other issues in this repository, so next steps are:

[ ] Merge existing PRs
[ ] Publish a new release
[ ] Update readme.md to indicate the fact that this is now integrated in the platform on new releases
[ ] Put this repository read-only

@mitchelsellers do you want me to go ahead and do that or there are other things to do before this last release?
