### ISSUE TITLE
Uninstall from 9.x installation

### ISSUE THREAD

**Issue by james7342** [DNNCommunity/SecurityAnalyzer#46]
## Please summarize your question in one sentence
When uninstalling module from a 9.x insatalltion the security analyzer page is left in the personabar.

## Give a more extended description
With the new personabar there is no way to access the host pages anymore in order to remove the page.

## Steps to reproduce (if needed)
Dnn 8.X site upgraded to 9.x
Uninstall the Security Analyzer a sit’s now included in DNN 9.x
Page still remains in personabar with no way to remove.
![aaf7fb58-91fb-45ae-8cde-1d22bdb2f9ec](https://user-images.githubusercontent.com/27960723/50521953-479a6000-0a7d-11e9-8ba5-5dec530305d8.jpeg)

**Comment by james7342** [comment]
Found a way to remove it. Not sure exactly which one of the below solved it as I ended up having to restart application pool and clear cache in order to get the page to display. Of course I did this on a test site with backup. 

ParentID = My TabID of My Home Page

1. update Tabs set PortalID=0 where TabName = 'Security Analyzer'
2. update Tabs set ParentID=56 where TabName = 'Security Analyzer'
3. update Tabs set Level=0 where TabName = 'Security Analyzer'

After I set the above I Restarted Application Pool and Cleared Cache via Servers. I went back into the pages module and was able to see the page. I  then proceeded to delete it and remove from recycle bin. Page is now gone from Tabs Table.

**Comment by james7342** [comment]
Just did another test and it appears the only things I needed to modify were.
1. update Tabs set PortalID=0 where TabName = 'Security Analyzer'
2. update Tabs set ParentID=56 where TabName = 'Security Analyzer'

Would be nice if the uninstaller would clean up dedicated pages it created during installation.

**Comment by james7342** [comment]
Another issue. Once you uninstall the module the built in DNN 9.X Security Analyzer will fail on "CheckModuleHeaderAndFooter" task. This is due the uninstaller removing a common SP from the DB. I looked in the SQL providers files and recreated it and built in Security Analyzer is working again without error.

CREATE PROCEDURE {databaseOwner}[{objectQualifier}SecurityAnalyzer_GetModulesHasHeaderFooter]
AS
BEGIN
    SELECT * FROM {databaseOwner}[{objectQualifier}TabModules]
        WHERE (Header IS NOT NULL AND CONVERT(NVARCHAR(MAX), Header) <> N'') OR (Footer IS NOT NULL AND CONVERT(NVARCHAR(MAX), Footer) <> N'')
END
GO

**Comment by sleupold** [comment]
Your update statement do not delete a page, it just modifies the record to an invalid value with a chance not to show up, but also with the risk to interfere with future updates.

**Comment by james7342** [comment]
Correct. But it did allow me to see it in the normal Admin/Pages section to delete it. Prior it was under Host Page and as I'm sure you are aware are not viewable anymore in the PersonaBar.

**Comment by james7342** [comment]
Actually reread your comment. I do agree I could have modified them to a value the would have broke something, but the fact once the changes where made I was able to remove the page via the Admin/Page administration. I'm not sure how that would interfere with future upgrades. I didn't delete the Page/TabID via SQL.

**Comment by sleupold** [comment]
do you want to remove or display the page?

**Comment by james7342** [comment]
It all started by trying to uninstall version 8.1.3 of the module as it's no longer needed and wasn't removed prior to upgrade or it got installed per directions in security notice of 2017.1 in 9.1. Not sure the exact timing of things on that. 

Once the module was uninstalled it left the page link in the PersonaBar. Upon clinking the link you got a blank page. So I was trying to remove the page left behind from removal of the module. The module is no longer required as it’s built into DNN. I used the above steps to get the page to display in the admin/page section so I could delete it. Prior to the updates above it wasn’t displayed as it was a host page.

The page is created during installation of the module (FeatureController.cs)


 //Add Extensions Host Page
                    var moduleDefId = GetModuleDefinition("SecurityAnalyzer", "SecurityAnalyzer");
                    var auditPage = AddHostPage("Security Analyzer", "Audit site security for best practices.",                        "~/DesktopModules/DNNCorp/SecurityAnalyzer/Images/Extensions_16x16_Standard.png", "~/DesktopModules/DNNCorp/SecurityAnalyzer/Images/Extensions_32x32_Standard.png", true);
                    var moduleid = AddModuleToPage(auditPage, moduleDefId, "Security Analyzer",
               "~/DesktopModules/DNNCorp/SecurityAnalyzer/Images/Extensions_32x32_Standard.png");

**Comment by valadas** [comment]
We could add the sql to delete the Security Analyser page in the uninstall sql script I guess

**Comment by valadas** [comment]
As for the missing SP, I suggest logging that issue at https://github.com/dnnsoftware/Dnn.Platform and put a link back to this one

**Comment by james7342** [comment]
> We could add the sql to delete the Security Analyser page in the uninstall sql script I guess

With the page getting created as part of the installation and with the changes in 9.X around host pages it might not be a bad idea. Not sure if possible, but maybe check if it's DNN 9.X and if true uninstall, if not don't. Similar to the changes you've done with 8.1.5 and the version check. Not if sure if that is possible with the DNN install/uninstall framework.

**Comment by sleupold** [comment]
regarding admin/host pages for SA: the idea should be removing the pages, not make them visible for manual remove.

**Comment by sleupold** [comment]
Regarding the deleted stored procedure, this should be removed from the cleanup script, if DNN version > 9 -  otherwise it will break core functionality. Two different components should never use same procedure names.

**Comment by james7342** [comment]
> regarding admin/host pages for SA: the idea should be removing the pages, not make them visible for manual remove.

Agree, if the installation creates new page(s) it should remove the page(s) at time of uninstallation. The only time I see this as a problem would be in older versions of DNN where someone may have edited the page for some reason and added additional modules to it.

**Comment by valadas** [comment]
When the persona bar was implemented, the old management modules where automatically uninstalled and their pages removed, for some reason two things went wrong for the Security module.
1. The module should have been handled the same way, uninstalled and page deleted (this was never done for this one).
2. The two modules should have never used the same stored procedure name.

So I think we can use the issue created on Dnn.Platform to handle this situation better on the next upgrade ( Uninstall the module, delete the page, recreate the store procedure and maybe tables or whatever else had the same name ).

**Comment by EPTamminga** [comment]
Shouldn’t we change the PB version of the SA now so it will have it’s own (uniquely named) version of the SP?

**Comment by valadas** [comment]
Sounds good to me, but we should keep that conversation in this issue https://github.com/dnnsoftware/Dnn.Platform/issues/2525 to keep track since the fix for this would have to be done on the platform. I am closing this for now.
