### ISSUE TITLE
add the full path for all the files in security analyzer to mke it easy to determine if it is a malicious file or not

### ISSUE THREAD

**Issue by zyhfish** [DNNCommunity/SecurityAnalyzer#47]
using the security analyzer for files that contain the word 'rookit'. The following four files were found:

Security.resx (08/01/2018 14:30:57) 
LocalResources.en-US.resources (08/01/2018 14:36:41) 
View.ascx (08/01/2018 21:06:53) 
View.ascx.resx (08/01/2018 21:06:53)

After further digging I realized these files are all part of the security analyzer module and are perfectly fine. However, this would be more useful if the full path of the file were supplied so it would easy to locate the file in question to determine if it is a malicious file or not.

**Comment by valadas** [comment]
I am closing this issue as this module is obsolete as per #42
