### ISSUE TITLE
Fix build scripts so they package correctly

### ISSUE THREAD

**Issue by cathalconnolly** [DNNCommunity/SecurityAnalyzer#5]
The module was initially created via a template (christoc) and contains some standard build scripts that were not used in packaged. We need to either remove these scripts or update them to correctly package the module as they currently don't do so e.g. they don't factor in the "DNNCorp" top level folder

**Comment by valadas** [comment]
I just cloned and built without issues, I guess this was already fixed and nobody closed the issue. Closing now
