### ISSUE TITLE
Feature Request: Encrypt Web.Config

### ISSUE THREAD

**Issue by moorecreative** [DNNCommunity/SecurityAnalyzer#6]
A security tool that we used a while back in older DNN 5x was a tool (it was a dashboard plugin) that would allow you to Encrypt and UnEncrypt key sections of the web.config.

While encrypted, standard dnn functions all continued normally. We were just careful to unencrypt before doing any new dnn module install that we knew wrote to the web.config, but other than that, everything worked fine while encrypted.

The encryption would hash the main connection string and the legacy connection string sections in the web.config.

**Comment by bdukes** [comment]
This sounds like a good idea to me (though it could cause issues on web farms).

**Comment by valadas** [comment]
Closing, moved to https://github.com/dnnsoftware/Dnn.Platform/issues/2463
